version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - ./db/db.sqlite:/opt/app/db/db.sqlite
      - ./datos:/opt/app/datos
    ports:
      - 8000:8000
    