# Generated by Django 4.1.6 on 2023-02-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_plataforma_juego_id_plataforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='id_juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud.juego'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_red_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud.red_social'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud.usuario'),
        ),
    ]
