# Generated by Django 4.1.6 on 2023-02-13 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit_juego', models.CharField(max_length=120)),
                ('plataforma', models.CharField(max_length=100)),
                ('f_publicacion', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Red_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rom_red_social', models.CharField(max_length=45)),
                ('url_red_social', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_usuario', models.CharField(max_length=45)),
                ('nom_usuario', models.CharField(max_length=120)),
                ('email_usuario', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_mensaje', models.DateField(default=django.utils.timezone.now)),
                ('text_mensaje', models.CharField(max_length=250)),
                ('id_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.juego')),
                ('id_red_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.red_social')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario')),
            ],
        ),
    ]
