# Generated by Django 4.1.6 on 2023-02-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_plataforma_alter_juego_f_publicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='plataforma',
            new_name='id_plataforma',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='text_mensaje',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='red_social',
            old_name='url_red_social',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email_usuario',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nom_usuario',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='tit_juego',
        ),
        migrations.RemoveField(
            model_name='red_social',
            name='rom_red_social',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nick_usuario',
        ),
        migrations.AddField(
            model_name='juego',
            name='titulo',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='red_social',
            name='nombre',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nick',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nombre',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
