# Generated by Django 4.1.6 on 2023-02-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_mensaje_id_juego_alter_mensaje_id_red_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='f_publicacion',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
